version: '3'
services:
  redis:
    image: redis
    networks:
      - webnet
  db:
    image: 'mysql'
    container_name: 'typeorm-mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'memeFactory'
    volumes:
      - ./db/storage:/var/lib/mysql
  web:
    image: bclim1/meme-factory-backend
    ports:
      - 8000:8000
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
networks:
  webnet:
